# MongoDB credentials
[mongo_credentials]
connection_string = "mongodb+srv://sufyanmalik:QsjfIC74yTxCgrXH@cluster0.8awuxv8.mongodb.net"
database = "test_db"
collection = "test_collection"

# Snowflake credentials
[destination.snowflake.credentials]
username = "sufyan"
password = "xTwfVyLpGK44TDF"
host = "pgdgtoc-ee29791"
warehouse = "etl_warehouse"
database = "etl_db"
schema = "PUBLIC"
role = "ACCOUNTADMIN"
