# Snowflake credentials
[dagster_dlt_pipeline.destination.snowflake.credentials]
username = "sufyan"
password = "xTwfVyLpGK44TDF"
host = "pgdgtoc-ee29791"
warehouse = "etl_warehouse"
database = "etl_db"
schema = "PUBLIC"
role = "ACCOUNTADMIN"