# Use a lightweight base image with Python 3.11 pre-installed
FROM python:3.11-slim

# Copy the app.py file from your current directory to the root of the image
COPY app.py .

# Tell Docker to run this command when a container is started from this image
CMD ["python", "app.py"]
