[credentials]
username = "postgres"              # <-- replace with your Postgres username
password = "pakistan"    # <-- replace with your Postgres password
host = "localhost"
port = 5432
database = "sufyan"    # <-- replace with your DB name
