# Use official Python image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy Python file into image
COPY hello.py .

# Default command when container runs
CMD ["python", "hello.py"]
