FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y gcc

# Set working directory inside container 
WORKDIR /app

# Copy dependencies file and install
COPY requirements.txt .

# -r means read from file
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project into container (folder within folder)
COPY . . 

# Expose port for Dagster UI
EXPOSE 3000

# Run Dagster webserver
CMD ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000"]

#-h Host , and -p is port
