#file to easily define and manage multiple Docker containers (like services) for a project — in a single file, using simple syntax.

version: "3.9"

services:
  dagster:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DAGSTER_HOME: /app
    command: ["dagster", "dev", "-h", "0.0.0.0", "-p", "3000"]
