[sources.chess]
secret_str = "<configure me>" # fill this in!

[destination.postgres.credentials]
database = "sufyan" # fill this in!
password = "Pakistan" # fill this in!
username = "postgres" # fill this in!
host = "localhost" # fill this in!
port = 5432
connect_timeout = 15
