# Postgres credentials
[postgres.credentials]
database = "sufyan"
username = "postgres"
password = "pakistan"
host = "localhost"
port = 5432

# Snowflake credentials
[destination.snowflake.credentials]
username = "sufyan"
password = "xTwfVyLpGK44TDF"
host = "pgdgtoc-ee29791"
warehouse = "etl_warehouse"
database = "etl_db"
schema = "PUBLIC"
role = "ACCOUNTADMIN"
