FROM python:3.10-slim

#LABEL for metadata
LABEL maintainer="you@example.com"
LABEL version="1.0"
LABEL description="Inspect demo container"

WORKDIR /app

# you can see this in json output
ENV MY_ENV_VAR="test-value"

COPY app.py .

CMD ["python", "app.py"]
